# Generated by Django 3.0.7 on 2020-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
